name: Crash Report
description: "File a crash report to FiveM, RedM, or FXServer, result is simple: you crashed"
labels: ["crash", "triage"]
assignees:
  - 

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this crash report.
        Only crash related issues are accepted, so please refrain yourself from submitting any other requests, including support requests.
        
        For issues, like exceptions, that don't crash the client or server use the [Bug Report](./new?assignees=&labels=bug%2Ctriage&projects=&template=bug_report.yml) template.
        
        \* Issue reports that fail to deliver the proper information may be closed without any feedback.
  
  - type: textarea
    id: result
    attributes:
      label: Crash results
      description: |
        What are the results of the crash? e.g.: log files, dumps, errors
      placeholder: 
    validations:
      required: true
  
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: |
        This is important to us. Fill in the exact steps you took, test and remove any steps that aren't relevant.
      placeholder: |
        1. 
        2. 
        3. 
        4. 
      render: bash
    validations:
      required: true
  
  - type: dropdown
    id: products
    attributes:
      label: Product(s)
      multiple: true
      description: |
        What products does this issue apply to?
      options:
        - FiveM
        - RedM
        - FXServer
        - FxDK
    validations:
      required: true
  
  - type: input
    id: build-number
    attributes:
      label: Specific version(s)
      description: Please fill in the build numbers of the products this issue occured on
      placeholder: FiveM/RedM 6464, Server 6402 windows/linux
    validations:
      required: true
  
  - type: textarea
    id: misc
    attributes:
      label: Additional information
      description: |
        Anything else you'd like to add?
