name: Build windows product

on:
  workflow_call:
    inputs:
      program:
        required: true
        type: string
      os:
        required: true
        type: string

env:
  PROGRAM: ${{ inputs.program }}

jobs:
  build_windows:
    name: Windows
    runs-on: ${{ github.event.inputs.os == 'windows' && 'windows-latest' || 'ubuntu-latest' }}
    steps:
      - name: Build
        if: ${{ github.event.inputs.os == 'windows' }}
        run: |
          :: D is too small, C is big enough
          mkdir C:\b
          cd /d C:\b
          
          py -3 -m pip install jinja2 ply
          
          :: dependencies
          mkdir dep
          
          :: download boost
          cd dep
          curl -s -L https://boostorg.jfrog.io/artifactory/main/release/1.71.0/source/boost_1_71_0.7z -o boost.7z
          7z -bso0 x boost.7z -oboost
          del boost.7z
          set BOOST_ROOT=%cd%\boost\boost_1_71_0
          cd ../
          
          git clone --depth=1 --quiet --shallow-submodules https://github.com/thorium-cfx/fivem-templates.git %PROGRAM% -c core.symlinks=true
          cd %PROGRAM%
          set REPO_ROOT=%cd%
          
          git submodule update --jobs=16 --init --depth=1
          call fxd get-chrome
          call prebuild.cmd
          
          call fxd gen -game %PROGRAM%
          
          cd code\build\%PROGRAM%\
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MsBuild.exe" CitizenMP.sln -t:build -restore -p:RestorePackagesConfig=true -p:preferredtoolarchitecture=x64 -p:configuration=release -maxcpucount:4 -v:q
        shell: cmd
        
      - name: Build2
        if: ${{ github.event.inputs.os == 'linux' }}
        run: echo hi
