name: Remove triage
on:
  issues:
    types:
      - closed
      - deleted
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            try
            {
                github.request('DELETE /repos/{owner}/{repo}/issues/{issue_number}/labels/{name}', {
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: 'triage',
                    headers: {
                        'X-GitHub-Api-Version': '2022-11-28'
                    }
                })
            
                /*github.rest.issues.removeLabel({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: ["triage"]
                });*/
            }
            catch (exception)
            {
                console.log(exception);
            }