name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            
            
            const productsStringRegex = /### Product\(s\)\s*([\w,\h]*)/;
            var productsString = productsRegex.exec(github.event.issue.body);
            
            console.log(productsString);
            
            const productsArrayRegex = /(\w+)[,\s]?/g;
            console.log(productsArrayRegex.exec(productsString));
            
            console.log(github.event.issue.body);
          
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["triage"]
            })