name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
env:
  ISSUE_BODY: ${{ github.event.issue.body }}

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            var addLabels = ["triage"];
            
            const issueBody = process.env.ISSUE_BODY;
            
            const productsStringRegex = /### Product\(s\)\s*([\w, ]*)/;            
            var productsString = productsStringRegex.exec(issueBody);
            var products = productsString[1].split(/[ ,]+/);
                        
            for (var i = 0; i < products.length; ++i)
            {
              const product = products[i];
              switch (product)
              {
                case "FxDK": addLabels.push("sdk"); break;
              }
            }
            
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: addLabels
            })