name: Validate PR
on:
  pull_request:
    types: [ reopened, opened, edited, synchronize ]

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      PR_REF: ${{ github.event.pull_request.head.sha }}
      COMMITS_URL: ${{ github.event.pull_request.commits_url }}
    steps:
      - run: |
          #commits=$(curl "$COMMITS_URL")
          #echo "$commits"
          readarray -t commitTitles < <(curl -k "$COMMITS_URL" | jq '.[].commit.message' )
          #printf '%s\n' "${arr[@]}"
          
          # first " character may exist due to how jq passes values
          commitTitleRegex="^\"?(tweak|fix|feat)\([a-zA-Z0-9/-]+\): .{10,}$"
          valid=true
          
          for (( i=0; i < ${#commitTitles[@]}; i++ )); do
            message=${commitTitles[$i]}
            if [[ "$message" =~ $commitTitleRegex ]]; then
              echo "  valid '$message'"
            else
              echo "invalid '$message'"
              valid=false
            fi
          done
        
          if [[ $valid = false ]]; then
            echo "bad!"
            exit 1
          fi
