name: Validate PR
on:
  pull_request:
    types: [ reopened, opened, edited, synchronize ]

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      COMMITS_URL: ${{ github.event.pull_request.commits_url }}
    steps:
      - name: Check commit titles
        run: |
          # get commits json and make an array of commit messages
          readarray -t commitMessages < <(curl -k "$COMMITS_URL" | jq '.[].commit.message' )
          
          # first " character may exist due to how jq passes values
          commitTitleRegex="^\"?(tweak|fix|feat)\([a-zA-Z0-9/-]+\): .{10,}$"
          valid=true
          
          for (( i=0; i < ${#commitMessages[@]}; i++ )); do
            message=${commitMessages[$i]}
            if [[ "$message" =~ $commitTitleRegex ]]; then
              echo "  valid '$message'"
            else
              echo "invalid '$message'"
              valid=false
            fi
          done
          
          if [[ $valid = false ]]; then
            echo "bad!"
            exit 1
          fi
      
      - name: Inform the user of bad titles
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "One or more of your commit titles does not conform to our title rules, make sure they all follow the following pattern: type(component): description. Allowed types are: fix, tweak, or feat and description must at least be 10 characters long to convey any meaning."
            });
