name: Validate PR
on:
  pull_request:
    types: [ reopened, opened, edited, synchronize ]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
        commitTitleRegex="^(tweak|fix|feat)\([a-zA-Z0-9/-]+\): .+$"
        valid=1
        
        while read line; do
            if [[ "$line" =~ $commitTitleRegex ]]; then
                echo "  valid '$line'"
            else
                echo "invalid '$line'"
                valid=0
            fi
        done <<< $(git log main.. --pretty="%s")
        
        if [[ $valid = 0 ]]; then
            echo "bad!"
            exit 1
        fi
