name: Validate PR
on:
  pull_request:
    types: [ reopened, opened, edited, synchronize ]

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      PR_REF: ${{ github.event.pull_request.head.sha }}
      COMMIT_NR: ${{ github.event.pull_request.commits }}
      COMMIT_NAMES: ${{ github.event.pull_request.commits[0].message }}
    steps:
      - run: |
          echo "$COMMIT_NR"
          echo "$COMMIT_NAMES"
          git clone $PR_REF --no-checkout
          
          commitTitleRegex="^(tweak|fix|feat)\([a-zA-Z0-9/-]+\): .+$"
          valid=true
          
          while read line; do
            if [[ "$line" =~ $commitTitleRegex ]]; then
              echo "  valid '$line'"
            else
              echo "invalid '$line'"
              valid=false
            fi
          done <<< $(git log main.. --pretty="%s")
        
          if [[ $valid = false ]]; then
            echo "bad!"
            exit 1
          fi
