name: Remove triage
on:
  issues:
    types:
      - closed

jobs:
  label_issues:
    steps:
    - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["triage"]
            })